// This file is autogenerated. Changes will be overwritten.
#include "VU2PALRVTW/moc_AudioClient.cpp"
#include "VU2PALRVTW/moc_CoreClient.cpp"
#include "VU2PALRVTW/moc_PowerClient.cpp"
#include "VU2PALRVTW/moc_backendmanager.cpp"
